// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las migraciones necesitan una conexión directa (sin pooler): la conexión
    // "pooled" de Neon no soporta bien los advisory locks que usa `migrate deploy`.
    // Esto solo afecta a la CLI de Prisma (generate/migrate); la app en tiempo de
    // ejecución sigue usando DATABASE_URL directamente en src/lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
